"""followers

Revision ID: 0684a94bab10
Revises: bf644ba78442
Create Date: 2018-08-07 21:23:33.740367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0684a94bab10'
down_revision = 'bf644ba78442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
